version: '3.3'

services:
  db:
    image: mysql:8.0.31
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - '33306:3306'
